columns:
  Item_Identifier: category
  Item_Weight: float
  Item_Fat_Content: category
  Item_Visibility: float
  Item_Type: category
  Item_MRP: float
  Outlet_Establishment_Year: float
  Outlet_Size: category
  Outlet_Location_Type: category
  Outlet_Type: category
  Item_Outlet_Sales: float
  Outlet_Identifier: category



numerical_columns:
  - Item_Weight
  - Item_Visibility
  - Item_MRP
  - Outlet_age



categorical_columns:
  - Item_Identifier
  - Item_Fat_Content
  - Outlet_Size
  - Outlet_Location_Type
  - Outlet_Type





target_column: Item_Outlet_Sales

domain_value:
  Item_Identifier:
    - FD
    - DR
    - NC 
  
  Item_Fat_Content:
    - Low Fat
    - Regular
    - Non Edible
  
  Outlet_Size:
    - Medium
    - High
    - Small
  
  Outlet_Location_Type:
  - Tier 1
  - Tier 3
  - Tier 2

  Outlet_Type:
  - Supermarket Type2
  - Supermarket Type1
  - Grocery Store
  - Supermarket Type3

  Item_Type:
  - Dairy
  - Soft Drinks
  - Meat
  - Fruits and Vegetables
  - Household
  - Baking Goods
  - Snack Foods
  - Frozen Foods
  - Breakfast
  - Health and Hygiene
  - Hard Drinks
  - Canned
  - Breads
  - Starchy Foods
  - Others
  - Seafood

  Outlet_Identifier:
  - OUT049
  - OUT018
  - OUT010
  - OUT013
  - OUT027
  - OUT045
  - OUT017
  - OUT046
  - OUT035
  - OUT019





